[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps =
  adafruit/Adafruit GFX Library @ ^1.11.10
  adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.4
build_unflags = -std=gnu++11
build_flags =
  -std=gnu++17
  -D ZO_FW_VERSION=\"3.0\"
  -D ZO_API_VERSION=\"3.0\"
  -D ZO_BUILD_DATE=\"${UNIX_TIME}\"
  -D ZO_FEATURE_WIFI=1
  -D ZO_FEATURE_HTTPS=1
  -D ZO_FEATURE_OTA=0
